class CountryCodes {
  static final List<Map<String, String>> codes = [
    {'name': 'Afghanistan', 'code': '+93', 'iso': 'AF'},
    {'name': 'Algeria', 'code': '+213', 'iso': 'DZ'},
    {'name': 'Argentina', 'code': '+54', 'iso': 'AR'},
    {'name': 'Australia', 'code': '+61', 'iso': 'AU'},
    {'name': 'Bangladesh', 'code': '+880', 'iso': 'BD'},
    {'name': 'Brazil', 'code': '+55', 'iso': 'BR'},
    {'name': 'Canada', 'code': '+1', 'iso': 'CA'},
    {'name': 'China', 'code': '+86', 'iso': 'CN'},
    {'name': 'Egypt', 'code': '+20', 'iso': 'EG'},
    {'name': 'France', 'code': '+33', 'iso': 'FR'},
    {'name': 'Germany', 'code': '+49', 'iso': 'DE'},
    {'name': 'Ghana', 'code': '+233', 'iso': 'GH'},
    {'name': 'India', 'code': '+91', 'iso': 'IN'},
    {'name': 'Indonesia', 'code': '+62', 'iso': 'ID'},
    {'name': 'Iran', 'code': '+98', 'iso': 'IR'},
    {'name': 'Iraq', 'code': '+964', 'iso': 'IQ'},
    {'name': 'Italy', 'code': '+39', 'iso': 'IT'},
    {'name': 'Japan', 'code': '+81', 'iso': 'JP'},
    {'name': 'Jordan', 'code': '+962', 'iso': 'JO'},
    {'name': 'Kenya', 'code': '+254', 'iso': 'KE'},
    {'name': 'Kuwait', 'code': '+965', 'iso': 'KW'},
    {'name': 'Lebanon', 'code': '+961', 'iso': 'LB'},
    {'name': 'Libya', 'code': '+218', 'iso': 'LY'},
    {'name': 'Malaysia', 'code': '+60', 'iso': 'MY'},
    {'name': 'Morocco', 'code': '+212', 'iso': 'MA'},
    {'name': 'Nigeria', 'code': '+234', 'iso': 'NG'},
    {'name': 'Pakistan', 'code': '+92', 'iso': 'PK'},
    {'name': 'Philippines', 'code': '+63', 'iso': 'PH'},
    {'name': 'Qatar', 'code': '+974', 'iso': 'QA'},
    {'name': 'Russia', 'code': '+7', 'iso': 'RU'},
    {'name': 'Saudi Arabia', 'code': '+966', 'iso': 'SA'},
    {'name': 'South Africa', 'code': '+27', 'iso': 'ZA'},
    {'name': 'Spain', 'code': '+34', 'iso': 'ES'},
    {'name': 'Sudan', 'code': '+249', 'iso': 'SD'},
    {'name': 'Syria', 'code': '+963', 'iso': 'SY'},
    {'name': 'Tunisia', 'code': '+216', 'iso': 'TN'},
    {'name': 'Turkey', 'code': '+90', 'iso': 'TR'},
    {'name': 'UAE', 'code': '+971', 'iso': 'AE'},
    {'name': 'UK', 'code': '+44', 'iso': 'GB'},
    {'name': 'USA', 'code': '+1', 'iso': 'US'},
    {'name': 'Yemen', 'code': '+967', 'iso': 'YE'},
  ];
}
