// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJrhCOGRE9g9fr6XHaejHddn_OM87bQs',
    appId: '1:71341780962:web:38c2e442a48a9d8e3bd3bb',
    messagingSenderId: '71341780962',
    projectId: 'souqe-app-3b137',
    authDomain: 'souqe-app-3b137.firebaseapp.com',
    storageBucket: 'souqe-app-3b137.firebasestorage.app',
    measurementId: 'G-KR9E3REXXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Mgy10EoyyMWKhoXPXpE12szr2XXbOK0',
    appId: '1:71341780962:android:2dbfc1bf362e7e053bd3bb',
    messagingSenderId: '71341780962',
    projectId: 'souqe-app-3b137',
    storageBucket: 'souqe-app-3b137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuws71d-hFEAFra0ctX00G3p78GO_zmOo',
    appId: '1:71341780962:ios:f17dc7780edab8fb3bd3bb',
    messagingSenderId: '71341780962',
    projectId: 'souqe-app-3b137',
    storageBucket: 'souqe-app-3b137.firebasestorage.app',
    iosBundleId: 'com.example.souqe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuws71d-hFEAFra0ctX00G3p78GO_zmOo',
    appId: '1:71341780962:ios:f17dc7780edab8fb3bd3bb',
    messagingSenderId: '71341780962',
    projectId: 'souqe-app-3b137',
    storageBucket: 'souqe-app-3b137.firebasestorage.app',
    iosBundleId: 'com.example.souqe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvJrhCOGRE9g9fr6XHaejHddn_OM87bQs',
    appId: '1:71341780962:web:176a81bd556101333bd3bb',
    messagingSenderId: '71341780962',
    projectId: 'souqe-app-3b137',
    authDomain: 'souqe-app-3b137.firebaseapp.com',
    storageBucket: 'souqe-app-3b137.firebasestorage.app',
    measurementId: 'G-6MZ1JLRHTC',
  );
}
